In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("/content/Input.csv",encoding='latin-1')

In [10]:
df.head(5)

     Name          Email    Age      City
0  Nitish   nr@gmail.com   23.0  Kolkatta
1   Virat   Vk@gmail.com   12.0  Banglore
2  Chrish   cg@gmail.com   45.0    Panjab
3     Abd  ABD@gmail.com    NaN     Delhi
4   Rohit   rs@gmail.com  120.0    Mumbai

In [11]:
# Checking missing values

df.isnull().sum()

Name     0
Email    1
Age      1
City     1
dtype: int64

### Handiling Missing value

In [12]:

df['Email'] = df['Email'].fillna('unknown@gmail.com') #missing value correction
df['Age'] = df['Age'].fillna(df['Age'].mean()) # Missing Value Correction
df['City'] = df['City'].fillna('unknown') #missing value correction

df

     Name              Email         Age      City
0  Nitish       nr@gmail.com   23.000000  Kolkatta
1   Virat       Vk@gmail.com   12.000000  Banglore
2  Chrish       cg@gmail.com   45.000000    Panjab
3     Abd      ABD@gmail.com   73.777778     Delhi
4   Rohit       rs@gmail.com  120.000000    Mumbai
5   Dhoni       ms@gmail.com  154.000000    Chenai
6    Iyer  unknown@gmail.com   78.000000  Rajsthan
7   Rahul       Kl@gmail.com   98.000000   Gujarat
8  Morgan       Om@gmail.com   89.000000   unknown
9  Sachin       st@gmail.com   45.000000   Lakhnov

In [14]:
# Fixing messy email
import re
def is_valid_email(email):
    pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
    return bool(re.match(pattern, str(email)))

# Store invalid rows
invalid_rows = df[~df['Email'].apply(is_valid_email)]

# Save invalid rows (optional but good)
invalid_rows.to_csv("invalid_data.csv", index=False)

# Keep only valid rows
df = df[df['Email'].apply(is_valid_email)]

In [15]:
# Fixing age with inproper number
for idx, i in enumerate(df['Age']):
    if i < 0 or i > 120:
        df.at[idx, 'Age'] = df['Age'].mean()
df

     Name              Email         Age      City
0  Nitish       nr@gmail.com   23.000000  Kolkatta
1   Virat       Vk@gmail.com   12.000000  Banglore
2  Chrish       cg@gmail.com   45.000000    Panjab
3     Abd      ABD@gmail.com   73.777778     Delhi
4   Rohit       rs@gmail.com  120.000000    Mumbai
5   Dhoni       ms@gmail.com   73.777778    Chenai
6    Iyer  unknown@gmail.com   78.000000  Rajsthan
7   Rahul       Kl@gmail.com   98.000000   Gujarat
8  Morgan       Om@gmail.com   89.000000   unknown
9  Sachin       st@gmail.com   45.000000   Lakhnov

In [16]:
df['Email'] = df['Email'].str.lower() # Validate Email
df

     Name              Email         Age      City
0  Nitish       nr@gmail.com   23.000000  Kolkatta
1   Virat       vk@gmail.com   12.000000  Banglore
2  Chrish       cg@gmail.com   45.000000    Panjab
3     Abd      abd@gmail.com   73.777778     Delhi
4   Rohit       rs@gmail.com  120.000000    Mumbai
5   Dhoni       ms@gmail.com   73.777778    Chenai
6    Iyer  unknown@gmail.com   78.000000  Rajsthan
7   Rahul       kl@gmail.com   98.000000   Gujarat
8  Morgan       om@gmail.com   89.000000   unknown
9  Sachin       st@gmail.com   45.000000   Lakhnov

In [17]:
# Standardize text fields
df['Name'] = df['Name'].str.title()
df['Email'] = df['Email'].str.lower()

In [18]:
# Derived fields

def age_group(age):
  if age <= 18:
    return 'Teen'
  elif age <= 30:
    return 'Young'
  elif age <= 50:
    return 'Middle'
  else:
    return 'Old'
df['Age Group'] = df['Age'].apply(age_group)
df

     Name              Email         Age      City Age Group
0  Nitish       nr@gmail.com   23.000000  Kolkatta     Young
1   Virat       vk@gmail.com   12.000000  Banglore      Teen
2  Chrish       cg@gmail.com   45.000000    Panjab    Middle
3     Abd      abd@gmail.com   73.777778     Delhi       Old
4   Rohit       rs@gmail.com  120.000000    Mumbai       Old
5   Dhoni       ms@gmail.com   73.777778    Chenai       Old
6    Iyer  unknown@gmail.com   78.000000  Rajsthan       Old
7   Rahul       kl@gmail.com   98.000000   Gujarat       Old
8  Morgan       om@gmail.com   89.000000   unknown       Old
9  Sachin       st@gmail.com   45.000000   Lakhnov    Middle

In [19]:
# export in output.csv
df.to_csv('output.csv',index = False)

## Error Handling

In [20]:
try:
    df = pd.read_csv('output.csv')
except FileNotFoundError:
    print("File not found. Check file name or path.")

In [21]:
#Handling incorrect data formats
try:
    df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
except Exception as e:
    print("Error in data format:", e)

In [22]:
try:
    #Full pipline
    df = pd.read_csv('output.csv')
    df['Age'] = df['Age'].fillna(df['Age'].mean())
    df.to_csv('output.csv', index=False)

except Exception as e:
    print("Something went wrong:", e)

In [26]:
chunks = pd.read_csv("/content/Input.csv", chunksize=1000)
cleaned_chunks = []
for chunk in chunks:
    # Apply your cleaning steps here

    chunk['Email'] = chunk['Email'].str.lower()

    chunk = chunk[chunk['Email'].apply(is_valid_email)]

    chunk.loc[(chunk['Age'] < 0) | (chunk['Age'] > 120), 'Age'] = chunk['Age'].mean()

    cleaned_chunks.append(chunk)

# Combine all chunks
df = pd.concat(cleaned_chunks)

# Save final cleaned data
df.to_csv("cleaned_data.csv", index=False)